name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex fonts-noto

    - name: Convert Markdown files to PDF
      run: |
        for file in *.md; do
          if [ -f "$file" ]; then
            pandoc "$file" -o "${file%.md}.pdf" --pdf-engine=xelatex -V mainfont="Noto Sans" -V "geometry:margin=1in"
          fi
        done

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PDF-files
        path: ./*.pdf
