name: Docs to PDF
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: .
