name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: output
          build_html: false
          build_pdf: true

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: output/
